sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t libstorage-ng-image .
script:
  # run the travis script
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" libstorage-ng-image ./.travis.sh

git:
  depth: 9999999
